---
- name: update records
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    username: "{{ lookup('env', 'SN_USERNAME') }}"
    password: "{{ lookup('env', 'SN_PASSWORD') }}"
    instance: "{{ lookup('env', 'SN_HOST') }}"
    mapping:
      problem:
        state:
          1: "open"
          2: "known_error1"
          3: "pending_change"
          4: "closed_resolved"
          5: "closed"

  tasks:

  - name: assign problem  
    servicenow.itsm.problem:
      problem_mapping: "{{ mapping.problem }}"
      assigned_to: "Ron.Kettering"
      number: PRB0040326

  - name: update problem state 
    servicenow.itsm.problem:
      problem_mapping: "{{ mapping.problem }}"
      state: known_error1
      number: PRB0040326
