- name: Called in response to VM ordered
  hosts: localhost
  tasks:
    - name: Update the comments field on a specific RITM
      servicenow.itsm.api:
        resource: sc_req_item 
        action: patch
        sys_id: "{{ ansible_eda.event.enriched_event.ritm_details[0].sys_id.value }}" 
        data:
          comments: |
            Comment published by Ansible Automation Platform
            Request item variables from event received:
            {{ ansible_eda.event.enriched_event.ritm_details[0].variables }}
      register: update_result

    - name: Display the result
      debug:
        var: update_result
